/**
 * Divided by username @ hostname.
 *  - username is generated by randomizer
 *    (my cats names).
 *  - hostname is generated by randomizer
 *    (my pc names).
 *  - I use (:) as a prefix for the path.
 *  - I use (-) as a suffix for the prompt.
 */
export default function TerminalPrompt() {
    return (
        <span>
            <span className="text-[#00FFFF]">
                g0d3nc14@
            </span>
            <span className="text-[#5555FF]">
                cloud:-
            </span>
            <span className="text-[#FF414C]">
                $
            </span>
        </span>
    );
}